[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPatterns = ["relay-cafe-api/**"]

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
